### ISSUE TITLE
possible missing asset

### ISSUE THREAD

**Issue by StoneCypher** [transatomic/reactor#5]
readme's whitepapers paragraph mentions four things:

1. Whitepapers describing the overall design of the TAP-520, 
1. the neutronics of the TAP-520, 
1. the zirconium hydride moderator, and 
1. the TPX microreactor design.

the first three are present in [the referenced directory](https://github.com/transatomic/reactor/tree/master/white-papers) as assets.  the fourth, "tpx microreactor design," is not.

since that's the one i need to strike back at inspector gadget and his confounded niece and dog, i would appreciate confirmation

![image](https://user-images.githubusercontent.com/77482/50261183-3b007280-03c0-11e9-83ac-1e4c6db4f942.png)

**Comment by transatomic** [comment]
You're right! Thanks for noticing -- just added the doc.
